### PR TITLE
fix: fix passing metadata, update .gitignore

### PR DESCRIPTION
**Pull request by joein**

### CODE REVIEW

**Comment by MathiasSpanhove** [comment]
This doesn't solve the exception right? Since when I use metadata I still get the exact same error?
Am I missing something?

**Comment by joein** [comment]
@MathiasSpanhove 

No, `**kwargs` are still propagated to `QdrantBase` which does not have `__init__` method and then passed to `Object.__init__` which does not accept `**kwargs`.

It will be required to update `qdrant-client` to `1.5.3`

**Comment by MathiasSpanhove** [comment]
@joein Ah I missed the qdrant-client update, thank you for your quick response and solution.

**Comment by joein** [comment]
@MathiasSpanhove https://github.com/qdrant/qdrant-client/pull/292

**Comment by kacperlukawski** [comment]
I added the test to cover that case and temporarily restricted the supported qdrant-client version to `<1.5.0`. It will be released as a hotfix and another version will be released once `qdrant-client==1.5.3` is released.

**Review by kacperlukawski — APPROVED** [review]

**Pull request merged**
